{
 "title": "Customer API Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total deleted customers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(customer_api_http_requests_total{operation=\"delete\"}[60s])"
    }
   ]
  },
  {
   "title": "Total updated customers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(customer_api_http_requests_total{operation=\"update\"}[60s])"
    }
   ]
  },
  {
   "title": "Total created customers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(customer_api_http_requests_total{operation=\"create\"}[60s])"
    }
   ]
  }
 ]
}