apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
spec:
  template:
    spec:
      initContainers:
        - name: migration-healthcheck
          image: migration:0.1
          command: ["sh", "-c", "yarn healthcheck; while [ $? -ne 0 ]; do yarn healthcheck; done"]
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret
      containers:
      - name: migration
        image: migration:0.1
        command: ["yarn", "migrate:up"]
        envFrom:
          - configMapRef:
              name: postgres-config
          - secretRef:
              name: postgres-secret
      restartPolicy: OnFailure
  ttlSecondsAfterFinished: 0
  backoffLimit: 5

