apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
spec:
  template:
    spec:
      containers:
      - name: migration
        image: migration:0.1
        command: ["yarn", "migrate:up"]
        env:
          - name: PG_HOST
            value: postgres-service
          - name: PG_PORT
            value: "5432"
          - name: PG_USER
            value: root
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                key: postgres-secret
          - name: PG_DATABASE
            value: app
        readinessProbe:
          exec:
            command:
              - "yarn healthcheck"
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: OnFailure
  ttlSecondsAfterFinished: 0
  backoffLimit: 5

