apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
     labels:
      app: server
    spec:
      containers:
        - image: server:0.1
          imagePullPolicy: Never
          name: server
          ports:
            - containerPort: 3000
