apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-definitions
data:
  definitions.json: |-
    {
        "rabbit_version": "3.10.1",
        "rabbitmq_version": "3.10.1",
        "product_name": "RabbitMQ",
        "product_version": "3.10.1",
        "users": [
            {
                "name": "admin",
                "password_hash": "gFlQns6Z0NFOYxZmKSDFRcKlyWbU3ksHjGjVzgKFCN5DsRb+",
                "hashing_algorithm": "rabbit_password_hashing_sha256",
                "tags": "administrator",
                "limits": {}
            }
        ],
        "vhosts": [
            {
                "name": "/"
            }
        ],
        "permissions": [
            {
                "user": "admin",
                "vhost": "/",
                "configure": ".*",
                "write": ".*",
                "read": ".*"
            }
        ],
        "queues": [
            {
                "name": "email",
                "vhost": "/",
                "durable": true,
                "auto_delete": false
            }
        ],
        "exchanges": [
            {
                "name": "custom-exchange",
                "vhost": "/",
                "type": "direct",
                "durable": true,
                "auto_delete": false,
                "internal": false,
                "arguments": {}
            }
        ],
        "bindings": [
            {
                "source": "custom-exchange",
                "vhost": "/",
                "destination": "email",
                "destination_type": "queue",
                "routing_key": "new-customer",
                "arguments": {}
            }
        ]
    }