apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
spec:
  image: 'rabbitmq:3.10.1-alpine'
  replicas: 1
  persistence:
    storageClassName: standard
    storage: 1Gi
  resources:
    requests:
      cpu: 256m
      memory: 1Gi
    limits:
      cpu: 256m
      memory: 1Gi
  service:
    type: LoadBalancer    
  override:
    statefulSet:
        spec:
          template:
            spec:
              containers:
                - name: rabbitmq
                  env:
                  - name: RABBITMQ_DEFAULT_USER
                    valueFrom:
                      secretKeyRef:
                        name: rabbitmq-secret
                        key: RABBITMQ_USERNAME
                  - name: RABBITMQ_DEFAULT_PASS
                    valueFrom:
                      secretKeyRef:
                        name: rabbitmq-secret
                        key: RABBITMQ_PASSWORD      
