apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
spec:
  image: 'rabbitmq:3.10.1-alpine'
  replicas: 1
  persistence:
    storageClassName: standard
    storage: 1Gi
  resources:
    requests:
      cpu: 256m
      memory: 1Gi
    limits:
      cpu: 256m
      memory: 1Gi
  rabbitmq:
    additionalConfig: |
      default_user = admin
      default_pass = qwerty
  service:
    type: LoadBalancer
