apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-sender-deployment
  labels:
    app: email-sender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-sender
  template:
    metadata:
     labels:
      app: email-sender
    spec:
      containers:
        - image: email-sender:0.1
          imagePullPolicy: Never
          name: email-sender
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: email-sender-secret   
            - configMapRef:
                name: email-sender-config
            - secretRef:
                name: rabbitmq-secret     
            - configMapRef:
                name: rabbitmq-config
